server:
  port: 8889
eureka:
  instance:
    hostname: pee1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://pee2:8888/eureka/
  server:
    enable-self-preservation: false #关闭Service自我保护功能
    eviction-interval-timer-in-ms: 4000 #设置清理间隔，毫秒为单位