server:
  port: 8888
spring:
  application:
    name: config-server
    #设置配置文件的远程仓库为github上的仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoumiaode/springCloundConfig.git
          search-paths: respo
          username: 1010467470@qq.com
          password: qw173974168
      label: master
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8889/eureka/
  instance:
    lease-expiration-duration-in-seconds: 1 #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 2 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,info,health